Add auth system
fencepos/fencepos pull request #21
Opened 2022-12-02 14:32 UTC by nerdylive123

2022-12-02 14:34 UTC, nerdylive123 commented
Alright waiting thanks

2022-12-02 16:39 UTC, jxpsert requested changes
2 comments

2022-12-02 16:39 UTC, jxpsert commented on server/app.js
> +    app = express();
Why did you remove ``const`` here?

2022-12-02 16:39 UTC, jxpsert commented on server/routes/auth.js
> +    router = express.Router();
Same here, why no ``const``?

2022-12-03 09:16 UTC, nerdylive123 commented on server/app.js
> +    app = express();
its the same

2022-12-03 09:16 UTC, nerdylive123 commented on server/routes/auth.js
> +    router = express.Router();
the same, shorter and easier to read

2022-12-03 09:17 UTC, jxpsert approved these changes
alrighty, looks fine

2022-12-03 09:17 UTC, merged